//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoASMXService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TodoItem", Namespace="http://www.xamarin.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class TodoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        private bool DoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Done {
            get {
                return this.DoneField;
            }
            set {
                if ((this.DoneField.Equals(value) != true)) {
                    this.DoneField = value;
                    this.RaisePropertyChanged("Done");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.xamarin.com/webservices/", ConfigurationName="ServiceReference1.TodoServiceSoap")]
    public interface TodoServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetTodoItemsResult de l'espace de noms http://www.xamarin.com/webservices/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/GetTodoItems", ReplyAction="*")]
        TodoASMXService.ServiceReference1.GetTodoItemsResponse GetTodoItems(TodoASMXService.ServiceReference1.GetTodoItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/GetTodoItems", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.GetTodoItemsResponse> GetTodoItemsAsync(TodoASMXService.ServiceReference1.GetTodoItemsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément item de l'espace de noms http://www.xamarin.com/webservices/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/CreateTodoItem", ReplyAction="*")]
        TodoASMXService.ServiceReference1.CreateTodoItemResponse CreateTodoItem(TodoASMXService.ServiceReference1.CreateTodoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/CreateTodoItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.CreateTodoItemResponse> CreateTodoItemAsync(TodoASMXService.ServiceReference1.CreateTodoItemRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément item de l'espace de noms http://www.xamarin.com/webservices/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/EditTodoItem", ReplyAction="*")]
        TodoASMXService.ServiceReference1.EditTodoItemResponse EditTodoItem(TodoASMXService.ServiceReference1.EditTodoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/EditTodoItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.EditTodoItemResponse> EditTodoItemAsync(TodoASMXService.ServiceReference1.EditTodoItemRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément id de l'espace de noms http://www.xamarin.com/webservices/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/DeleteTodoItem", ReplyAction="*")]
        TodoASMXService.ServiceReference1.DeleteTodoItemResponse DeleteTodoItem(TodoASMXService.ServiceReference1.DeleteTodoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/DeleteTodoItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.DeleteTodoItemResponse> DeleteTodoItemAsync(TodoASMXService.ServiceReference1.DeleteTodoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/CalculerFraisDeLivraison", ReplyAction="*")]
        double CalculerFraisDeLivraison(int km, int poids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/CalculerFraisDeLivraison", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculerFraisDeLivraisonAsync(int km, int poids);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodoItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodoItems", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.GetTodoItemsRequestBody Body;
        
        public GetTodoItemsRequest() {
        }
        
        public GetTodoItemsRequest(TodoASMXService.ServiceReference1.GetTodoItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTodoItemsRequestBody {
        
        public GetTodoItemsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodoItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodoItemsResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.GetTodoItemsResponseBody Body;
        
        public GetTodoItemsResponse() {
        }
        
        public GetTodoItemsResponse(TodoASMXService.ServiceReference1.GetTodoItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class GetTodoItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TodoASMXService.ServiceReference1.TodoItem[] GetTodoItemsResult;
        
        public GetTodoItemsResponseBody() {
        }
        
        public GetTodoItemsResponseBody(TodoASMXService.ServiceReference1.TodoItem[] GetTodoItemsResult) {
            this.GetTodoItemsResult = GetTodoItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTodoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTodoItem", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.CreateTodoItemRequestBody Body;
        
        public CreateTodoItemRequest() {
        }
        
        public CreateTodoItemRequest(TodoASMXService.ServiceReference1.CreateTodoItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class CreateTodoItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TodoASMXService.ServiceReference1.TodoItem item;
        
        public CreateTodoItemRequestBody() {
        }
        
        public CreateTodoItemRequestBody(TodoASMXService.ServiceReference1.TodoItem item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTodoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTodoItemResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.CreateTodoItemResponseBody Body;
        
        public CreateTodoItemResponse() {
        }
        
        public CreateTodoItemResponse(TodoASMXService.ServiceReference1.CreateTodoItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateTodoItemResponseBody {
        
        public CreateTodoItemResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditTodoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditTodoItem", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.EditTodoItemRequestBody Body;
        
        public EditTodoItemRequest() {
        }
        
        public EditTodoItemRequest(TodoASMXService.ServiceReference1.EditTodoItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class EditTodoItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TodoASMXService.ServiceReference1.TodoItem item;
        
        public EditTodoItemRequestBody() {
        }
        
        public EditTodoItemRequestBody(TodoASMXService.ServiceReference1.TodoItem item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditTodoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditTodoItemResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.EditTodoItemResponseBody Body;
        
        public EditTodoItemResponse() {
        }
        
        public EditTodoItemResponse(TodoASMXService.ServiceReference1.EditTodoItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditTodoItemResponseBody {
        
        public EditTodoItemResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTodoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTodoItem", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.DeleteTodoItemRequestBody Body;
        
        public DeleteTodoItemRequest() {
        }
        
        public DeleteTodoItemRequest(TodoASMXService.ServiceReference1.DeleteTodoItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class DeleteTodoItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteTodoItemRequestBody() {
        }
        
        public DeleteTodoItemRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTodoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTodoItemResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMXService.ServiceReference1.DeleteTodoItemResponseBody Body;
        
        public DeleteTodoItemResponse() {
        }
        
        public DeleteTodoItemResponse(TodoASMXService.ServiceReference1.DeleteTodoItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteTodoItemResponseBody {
        
        public DeleteTodoItemResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TodoServiceSoapChannel : TodoASMXService.ServiceReference1.TodoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodoServiceSoapClient : System.ServiceModel.ClientBase<TodoASMXService.ServiceReference1.TodoServiceSoap>, TodoASMXService.ServiceReference1.TodoServiceSoap {
        
        public TodoServiceSoapClient() {
        }
        
        public TodoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TodoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TodoASMXService.ServiceReference1.GetTodoItemsResponse TodoASMXService.ServiceReference1.TodoServiceSoap.GetTodoItems(TodoASMXService.ServiceReference1.GetTodoItemsRequest request) {
            return base.Channel.GetTodoItems(request);
        }
        
        public TodoASMXService.ServiceReference1.TodoItem[] GetTodoItems() {
            TodoASMXService.ServiceReference1.GetTodoItemsRequest inValue = new TodoASMXService.ServiceReference1.GetTodoItemsRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.GetTodoItemsRequestBody();
            TodoASMXService.ServiceReference1.GetTodoItemsResponse retVal = ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).GetTodoItems(inValue);
            return retVal.Body.GetTodoItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.GetTodoItemsResponse> TodoASMXService.ServiceReference1.TodoServiceSoap.GetTodoItemsAsync(TodoASMXService.ServiceReference1.GetTodoItemsRequest request) {
            return base.Channel.GetTodoItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.GetTodoItemsResponse> GetTodoItemsAsync() {
            TodoASMXService.ServiceReference1.GetTodoItemsRequest inValue = new TodoASMXService.ServiceReference1.GetTodoItemsRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.GetTodoItemsRequestBody();
            return ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).GetTodoItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TodoASMXService.ServiceReference1.CreateTodoItemResponse TodoASMXService.ServiceReference1.TodoServiceSoap.CreateTodoItem(TodoASMXService.ServiceReference1.CreateTodoItemRequest request) {
            return base.Channel.CreateTodoItem(request);
        }
        
        public void CreateTodoItem(TodoASMXService.ServiceReference1.TodoItem item) {
            TodoASMXService.ServiceReference1.CreateTodoItemRequest inValue = new TodoASMXService.ServiceReference1.CreateTodoItemRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.CreateTodoItemRequestBody();
            inValue.Body.item = item;
            TodoASMXService.ServiceReference1.CreateTodoItemResponse retVal = ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).CreateTodoItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.CreateTodoItemResponse> TodoASMXService.ServiceReference1.TodoServiceSoap.CreateTodoItemAsync(TodoASMXService.ServiceReference1.CreateTodoItemRequest request) {
            return base.Channel.CreateTodoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.CreateTodoItemResponse> CreateTodoItemAsync(TodoASMXService.ServiceReference1.TodoItem item) {
            TodoASMXService.ServiceReference1.CreateTodoItemRequest inValue = new TodoASMXService.ServiceReference1.CreateTodoItemRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.CreateTodoItemRequestBody();
            inValue.Body.item = item;
            return ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).CreateTodoItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TodoASMXService.ServiceReference1.EditTodoItemResponse TodoASMXService.ServiceReference1.TodoServiceSoap.EditTodoItem(TodoASMXService.ServiceReference1.EditTodoItemRequest request) {
            return base.Channel.EditTodoItem(request);
        }
        
        public void EditTodoItem(TodoASMXService.ServiceReference1.TodoItem item) {
            TodoASMXService.ServiceReference1.EditTodoItemRequest inValue = new TodoASMXService.ServiceReference1.EditTodoItemRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.EditTodoItemRequestBody();
            inValue.Body.item = item;
            TodoASMXService.ServiceReference1.EditTodoItemResponse retVal = ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).EditTodoItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.EditTodoItemResponse> TodoASMXService.ServiceReference1.TodoServiceSoap.EditTodoItemAsync(TodoASMXService.ServiceReference1.EditTodoItemRequest request) {
            return base.Channel.EditTodoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.EditTodoItemResponse> EditTodoItemAsync(TodoASMXService.ServiceReference1.TodoItem item) {
            TodoASMXService.ServiceReference1.EditTodoItemRequest inValue = new TodoASMXService.ServiceReference1.EditTodoItemRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.EditTodoItemRequestBody();
            inValue.Body.item = item;
            return ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).EditTodoItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TodoASMXService.ServiceReference1.DeleteTodoItemResponse TodoASMXService.ServiceReference1.TodoServiceSoap.DeleteTodoItem(TodoASMXService.ServiceReference1.DeleteTodoItemRequest request) {
            return base.Channel.DeleteTodoItem(request);
        }
        
        public void DeleteTodoItem(string id) {
            TodoASMXService.ServiceReference1.DeleteTodoItemRequest inValue = new TodoASMXService.ServiceReference1.DeleteTodoItemRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.DeleteTodoItemRequestBody();
            inValue.Body.id = id;
            TodoASMXService.ServiceReference1.DeleteTodoItemResponse retVal = ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).DeleteTodoItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.DeleteTodoItemResponse> TodoASMXService.ServiceReference1.TodoServiceSoap.DeleteTodoItemAsync(TodoASMXService.ServiceReference1.DeleteTodoItemRequest request) {
            return base.Channel.DeleteTodoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMXService.ServiceReference1.DeleteTodoItemResponse> DeleteTodoItemAsync(string id) {
            TodoASMXService.ServiceReference1.DeleteTodoItemRequest inValue = new TodoASMXService.ServiceReference1.DeleteTodoItemRequest();
            inValue.Body = new TodoASMXService.ServiceReference1.DeleteTodoItemRequestBody();
            inValue.Body.id = id;
            return ((TodoASMXService.ServiceReference1.TodoServiceSoap)(this)).DeleteTodoItemAsync(inValue);
        }
        
        public double CalculerFraisDeLivraison(int km, int poids) {
            return base.Channel.CalculerFraisDeLivraison(km, poids);
        }
        
        public System.Threading.Tasks.Task<double> CalculerFraisDeLivraisonAsync(int km, int poids) {
            return base.Channel.CalculerFraisDeLivraisonAsync(km, poids);
        }
    }
}
